# Generated by Django 5.2.5 on 2025-09-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='crete_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='crete_date',
            new_name='create_date',
        ),
    ]
